import React from 'react';
import { LegalLayout } from '../../components/legal/LegalLayout';
import { LEGAL_INFO } from '../../types/legal';

interface PrivacyPolicyProps {
  onBack: () => void;
  onNavigate: (page: string) => void;
}

export function PrivacyPolicy({ onBack, onNavigate }: PrivacyPolicyProps) {
  return (
    <LegalLayout title="Privacy Policy" onBack={onBack} onNavigate={onNavigate}>
      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Introduction</h2>
        <p className="text-gray-700 mb-4">
          Welcome to {LEGAL_INFO.companyName}. We are committed to protecting your privacy and ensuring
          the security of your personal information. This Privacy Policy explains how we collect, use,
          disclose, and safeguard your information when you use our service.
        </p>
        <p className="text-gray-700">
          By using {LEGAL_INFO.companyName}, you agree to the collection and use of information in
          accordance with this policy. If you do not agree with our policies and practices, please do not
          use our service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Information We Collect</h2>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">1.1 Personal Information</h3>
        <p className="text-gray-700 mb-4">
          We collect the following personal information when you register and use our service:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Email address (required for account creation and authentication)</li>
          <li>Password (encrypted and securely stored)</li>
          <li>Account preferences and settings</li>
          <li>Payment information (processed securely through Stripe)</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">1.2 User-Generated Content</h3>
        <p className="text-gray-700 mb-4">
          When you use our service, we collect and store:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Startup ideas and business concepts you submit for validation</li>
          <li>Analysis results and reports generated by our AI system</li>
          <li>Refined ideas and improvement plans</li>
          <li>Your analysis history and saved reports</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">1.3 Usage Information</h3>
        <p className="text-gray-700 mb-4">
          We automatically collect certain information about your device and usage patterns:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>IP address and browser type</li>
          <li>Device information and operating system</li>
          <li>Pages visited and features used</li>
          <li>Time and date of visits</li>
          <li>Analysis submission frequency and patterns</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">2. How We Use Your Information</h2>
        <p className="text-gray-700 mb-4">
          We use the collected information for the following purposes:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>To create and manage your account</li>
          <li>To provide AI-powered startup idea validation and analysis</li>
          <li>To process subscription payments and manage billing</li>
          <li>To improve our service and develop new features</li>
          <li>To communicate with you about your account and service updates</li>
          <li>To enforce our Terms of Service and prevent fraud</li>
          <li>To comply with legal obligations</li>
          <li>To provide customer support and respond to inquiries</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">3. AI Processing and Data Usage</h2>
        <p className="text-gray-700 mb-4">
          Your startup ideas and business concepts are processed using artificial intelligence services
          to generate market validation reports and insights. This processing includes:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Analyzing your idea against market data and trends</li>
          <li>Generating competitive analysis and opportunity assessments</li>
          <li>Creating actionable recommendations and improvement plans</li>
        </ul>
        <p className="text-gray-700">
          We use third-party AI services to process your submissions. These services are bound by strict
          confidentiality agreements and do not use your data to train their models or for any purpose
          other than providing our service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Data Storage and Security</h2>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">4.1 Database Storage</h3>
        <p className="text-gray-700 mb-4">
          Your data is securely stored using Supabase, a secure and reliable database platform. All data
          is encrypted in transit and at rest. We implement industry-standard security measures including:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>SSL/TLS encryption for all data transmission</li>
          <li>Encrypted database storage</li>
          <li>Regular security audits and updates</li>
          <li>Role-based access controls</li>
          <li>Secure authentication using modern protocols</li>
        </ul>

        <h3 className="text-xl font-semibold text-gray-900 mb-3 mt-6">4.2 Payment Information</h3>
        <p className="text-gray-700 mb-4">
          All payment information is processed through Stripe, a PCI-DSS compliant payment processor.
          We do not store your credit card numbers or banking information on our servers. Stripe maintains
          the highest level of security certifications in the payments industry.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Information Sharing and Disclosure</h2>
        <p className="text-gray-700 mb-4">
          We do not sell, trade, or rent your personal information to third parties. We may share your
          information only in the following circumstances:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>
            <strong>Service Providers:</strong> With trusted third-party service providers who assist in
            operating our service (Supabase for database, Stripe for payments, AI providers for analysis)
          </li>
          <li>
            <strong>Legal Requirements:</strong> When required by law or to respond to legal process
          </li>
          <li>
            <strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets
          </li>
          <li>
            <strong>Protection of Rights:</strong> To protect the rights, property, or safety of
            {LEGAL_INFO.companyName}, our users, or others
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Data Retention</h2>
        <p className="text-gray-700 mb-4">
          We retain your personal information for as long as your account is active or as needed to
          provide you services. If you wish to delete your account, you may do so through your account
          settings or by contacting us.
        </p>
        <p className="text-gray-700">
          After account deletion, we will delete or anonymize your personal information within 30 days,
          except where retention is required for legal or legitimate business purposes (such as fraud
          prevention or legal compliance).
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Your Rights and Choices</h2>
        <p className="text-gray-700 mb-4">
          Depending on your location, you may have the following rights regarding your personal information:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>
            <strong>Access:</strong> Request a copy of the personal information we hold about you
          </li>
          <li>
            <strong>Correction:</strong> Request correction of inaccurate or incomplete information
          </li>
          <li>
            <strong>Deletion:</strong> Request deletion of your personal information
          </li>
          <li>
            <strong>Data Portability:</strong> Request a copy of your data in a machine-readable format
          </li>
          <li>
            <strong>Opt-Out:</strong> Opt-out of marketing communications (you'll still receive
            essential service emails)
          </li>
          <li>
            <strong>Withdraw Consent:</strong> Withdraw consent where we rely on consent to process
            your data
          </li>
        </ul>
        <p className="text-gray-700">
          To exercise any of these rights, please contact us at {LEGAL_INFO.contactEmail}.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">8. International Data Transfers</h2>
        <p className="text-gray-700 mb-4">
          {LEGAL_INFO.companyName} is based in {LEGAL_INFO.companyLocation}. Your information may be
          transferred to and processed in countries other than your country of residence. These countries
          may have data protection laws that are different from the laws of your country.
        </p>
        <p className="text-gray-700">
          We ensure that such transfers comply with applicable data protection laws and that appropriate
          safeguards are in place to protect your information.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">9. GDPR Compliance (EU Users)</h2>
        <p className="text-gray-700 mb-4">
          If you are located in the European Economic Area (EEA), you have additional rights under the
          General Data Protection Regulation (GDPR):
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Right to object to processing of your personal data</li>
          <li>Right to restriction of processing</li>
          <li>Right to lodge a complaint with a supervisory authority</li>
          <li>Right to be informed about data breaches</li>
        </ul>
        <p className="text-gray-700">
          We process your data based on one or more of the following legal grounds: consent, contract
          performance, legal obligation, or legitimate interests.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">10. CCPA Compliance (California Users)</h2>
        <p className="text-gray-700 mb-4">
          If you are a California resident, you have specific rights under the California Consumer
          Privacy Act (CCPA):
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Right to know what personal information is collected</li>
          <li>Right to know if personal information is sold or disclosed</li>
          <li>Right to opt-out of the sale of personal information (we do not sell your data)</li>
          <li>Right to deletion of personal information</li>
          <li>Right to non-discrimination for exercising your privacy rights</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">11. Children's Privacy</h2>
        <p className="text-gray-700 mb-4">
          Our service is not intended for children under the age of 18. We do not knowingly collect
          personal information from children under 18. If you are a parent or guardian and believe
          your child has provided us with personal information, please contact us immediately.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">12. Cookies and Tracking Technologies</h2>
        <p className="text-gray-700 mb-4">
          We use cookies and similar tracking technologies to enhance your experience. For detailed
          information about our use of cookies, please refer to our Cookie Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">13. Third-Party Links</h2>
        <p className="text-gray-700 mb-4">
          Our service may contain links to third-party websites or services. We are not responsible
          for the privacy practices of these third parties. We encourage you to read their privacy
          policies before providing any information.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">14. Data Breach Notification</h2>
        <p className="text-gray-700 mb-4">
          In the event of a data breach that affects your personal information, we will notify you
          and relevant authorities in accordance with applicable laws. We will inform you of the nature
          of the breach, the data affected, and the steps we are taking to address it.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">15. Changes to This Privacy Policy</h2>
        <p className="text-gray-700 mb-4">
          We may update this Privacy Policy from time to time to reflect changes in our practices or
          for legal, operational, or regulatory reasons. We will notify you of any material changes by:
        </p>
        <ul className="list-disc list-inside text-gray-700 mb-4 space-y-2">
          <li>Posting the updated policy on our website with a new "Last Updated" date</li>
          <li>Sending you an email notification (for significant changes)</li>
          <li>Displaying a prominent notice on our service</li>
        </ul>
        <p className="text-gray-700">
          Your continued use of our service after such changes constitutes your acceptance of the
          updated Privacy Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">16. Contact Information</h2>
        <p className="text-gray-700 mb-4">
          If you have any questions, concerns, or requests regarding this Privacy Policy or our data
          practices, please contact us at:
        </p>
        <div className="bg-gray-50 p-6 rounded-lg">
          <p className="text-gray-700 font-semibold">{LEGAL_INFO.companyName}</p>
          <p className="text-gray-700">{LEGAL_INFO.companyLocation}</p>
          <p className="text-indigo-600 font-semibold mt-2">{LEGAL_INFO.contactEmail}</p>
        </div>
      </section>
    </LegalLayout>
  );
}
